import { Inter } from 'next/font/google';
import './globals.css';
import Headers from '@/components/headers';

import { ClerkProvider } from '@clerk/nextjs';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className}`}>
          <main className="min-h-screen">
            {children}
            <Headers />
          </main>

          <footer className="bg-blue-50 py-12">
            <div className="container mx-auto px-4 text-center text-gray-900">
              <p>Made with ❤️ By Faizan Ahmad.</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
